version: '3.7'

services:
    redis:
        image: redis
        deploy:
            placement:
                constraints:
                  - node.labels.NFS == attached
                  - node.role == manager
            update_config:
                parallelism: 2
                delay: 10s
        volumes:
          - /nfs/pyromancer/Projects/Landscape_Fuel_Moisture_Project/data/redis/data:/data
        ports:
          - 6380:6379
        networks:
          - dash
          
    dash:
        image: anthonyrawlinsuom/dssh
        ports:
          - 8050:8050
        networks:
          - staging-network
          - dash
        volumes:
          - ./image/app.py:/app/app.py
          - ./image/index.py:/app/index.py
          - ./image/apps:/app/apps
          - ./image/assets:/app/assets
        deploy:
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                  - node.role == manager
                  - node.labels.NFS == attached
            labels:
              - traefik.backend.loadbalancer.swarm=true
              - traefik.docker.network=staging-network
              - traefik.enable=true
              - traefik.frontend.passHostHeader=true
              - traefik.frontend.rule=Host:dssh.cloud.bushfirebehaviour.net.au
              - traefik.port=8050
              - traefik.redirectorservice.frontend.entryPoints=http
              - traefik.redirectorservice.frontend.redirect.entryPoint=https
              - traefik.tags=staging-network
              - traefik.webservice.frontend.entryPoints=https
networks:
    dash:
        driver: overlay
        attachable: true
    staging-network:
        external: true